# NG Monitoring Server Configuration.

# Server address.
address = "0.0.0.0:12020"
advertise-address = "192.168.31.201:12020"

[log]
# Log path
path = "/data/tidb-deploy/prometheus-9090/log"

# Log level: INFO, WARN, ERROR
level = "INFO"

[pd]
# Addresses of PD instances within the TiDB cluster. Multiple addresses are separated by commas, e.g. "10.0.0.1:2379","10.0.0.2:2379"
endpoints = ["192.168.31.201:2379"]

[storage]
path = "/data/tidb-data/prometheus-9090"