---
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).
  external_labels:
    cluster: 'tidb-test'
    monitor: "prometheus"

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'node.rules.yml'
  - 'blacker.rules.yml'
  - 'bypass.rules.yml'
  - 'pd.rules.yml'
  - 'tidb.rules.yml'
  - 'tikv.rules.yml'
  - 'tikv.accelerate.rules.yml'
  - 'tiflash.rules.yml'
  - 'ticdc.rules.yml'
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - '192.168.31.201:9093'

scrape_configs:
  - job_name: "overwritten-nodes"
    honor_labels: true # don't overwrite job & instance labels
    static_configs:
    - targets:
      - '192.168.31.201:9100'
  - job_name: "tidb"
    honor_labels: true # don't overwrite job & instance labels
    static_configs:
    - targets:
      - '192.168.31.201:10080'
  - job_name: "tikv"
    honor_labels: true # don't overwrite job & instance labels
    static_configs:
    - targets:
      - '192.168.31.201:20180'
  - job_name: "pd"
    honor_labels: true # don't overwrite job & instance labels
    static_configs:
    - targets:
      - '192.168.31.201:2379'
  - job_name: "tiflash"
    honor_labels: true # don't overwrite job & instance labels
    static_configs:
    - targets:
       - '192.168.31.201:8234'
       - '192.168.31.201:20292'
  - job_name: "ticdc"
    honor_labels: true # don't overwrite job & instance labels
    static_configs:
    - targets:
      - '192.168.31.201:8300'
  - job_name: "ng-monitoring"
    honor_labels: true # don't overwrite job & instance labels
    static_configs:
    - targets:
      - '192.168.31.201:12020'
  - job_name: "tidb_port_probe"
    scrape_interval: 30s
    metrics_path: /probe
    params:
      module: [tcp_connect]
    static_configs:
    - targets:
      - '192.168.31.201:10080'
      labels:
        group: 'tidb'
    - targets:
      - '192.168.31.201:20180'
      labels:
        group: 'tikv'
    - targets:
      - '192.168.31.201:2379'
      labels:
        group: 'pd'
    - targets:
       - '192.168.31.201:8234'
      labels:
        group: 'tiflash'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.31.201:9115
  - job_name: "monitor_port_probe"
    scrape_interval: 30s
    metrics_path: /probe
    params:
      module: [tcp_connect]
    static_configs:
    - targets:
      - '192.168.31.201:3000'
      labels:
        group: 'grafana'
    - targets:
      - '192.168.31.201:9100'
      labels:
        group: 'node_exporter'
    - targets:
      - '192.168.31.201:9115'
      labels:
        group: 'blackbox_exporter'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.31.201:9115
  - job_name: "blackbox_exporter_192.168.31.201:9115_icmp"
    scrape_interval: 6s
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
    - targets:
      - '192.168.31.201'
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*)(:80)?
        target_label: __param_target
        replacement: ${1}
      - source_labels: [__param_target]
        regex: (.*)
        target_label: ping
        replacement: ${1}
      - source_labels: []
        regex: .*
        target_label: __address__
        replacement: 192.168.31.201:9115
